README.md

Added Meteor to Integration Section.

Added Meteor to Integration Section.

---

README.md

And include Vert.x Feeds, a simple RSS Aggregator.

Add a section for the examples

---

README.md

Sorry, my bad, lower-case anchor.

Broken anchor

---

README.md

Signed-off-by: Johannes Schüth <j.schueth[at]gentics.com>

Add spring-vertx-ext to list of dependency injection extensions

---

README.md

See
https://github.com/saffron-technology/vertx-eventbusbridge

Added Java implementation of vertxbus.js

---

README.md

https://github.com/aesteve/vertx-nubes

Adding Vertx-Nubes project to Web Frameworks

---

README.md

https://github.com/kohesive/kovert

added Kovert library

---

vert-x2.md

Add vertx-deploy-module

---

README.md

Added a link to vert.x awesomeness.

Added handlers to readme

---

README.md

Replacement for https://github.com/vert-x3/vertx-lang-js/pull/37
See also https://groups.google.com/forum/#!searchin/vertx/node.js/vertx/zJWsHXBOizg/ShhyznYiBgAJ

Update README.md to add link to Node.js Service Factory

---

README.md

Hello,
Hope adding the new sub category is okay. Let me know if you want to change anything. 
Regards
Fuzz

Added Vert.x Hot to new sub section: Development Tools

---

README.md

Enjoy as part of a healthy diet

Add Vert.x Groovy Sugar

---

README.md

add Java and Android Event Bus client

add Java and Android Event Bus client

---

README.md

Added [Gateleen](https://github.com/swisspush/gateleen) project under new middleware section

Added Gateleen project

---

README.md

Added [vertx-redisques](https://github.com/swisspush/vertx-redisques) project

Added vertx-redisques project

---

README.md

Added [vertx-rest-storage](https://github.com/swisspush/vertx-rest-storage) project

Added vertx-rest-storage project

---

README.md

hope the place fits, cause its both, relational and document

added vertx-pojo-mapper

---

README.md

Added Server-Sent Events implementation in the "Integration" section

jEaSSE: Server-Sent Events implementation

---

README.md

As Julie suggested. https://github.com/isaiah/jubilee/issues/27

add jubilee server to web framework section

---

README.md

- https://github.com/weld/weld-vertx/issues/2

Add weld-vertx to vert.x awesome

---

README.md

Signed-off-by: Dan O'Reilly <oreilldf@gmail.com>

Add entry for vertx-zeromq

---

README.md

I'd like to add this list to https://github.com/sindresorhus/awesome. According to the awesome manifesto (https://github.com/sindresorhus/awesome/blob/master/awesome.md) I added the badge and fixed the list's title.

Comply with awesome manifesto

---

README.md

Added vert.x cron to the utilities section. https://github.com/diabolicallabs/vertx-cron

added vertx-cron

---

README.md

https://github.com/hubrick/vertx-kafka-service

Kafka service pr

---

README.md

https://github.com/hubrick/vertx-rest-client

vertx rest client

---

README.md

Added own library that integrates vertx3 with Azure ServiceBus.

Add Azure ServiceBus client

---

README.md

window 1:
```
$ echo '{"this":"that"}' | vxc -n callback
```
window 2:
```
$ vxc -n callback -l
{"this":"that"}
```

Command line client for vertx bus 

---

README.md

Thanks for merging previous PR. As said, I would follow up with this one :)

Add vertx-graphql-service-discovery to Microservices section

---

README.md

Add an entry for vertx-async library

Add vertx-async library

---

README.md

@pmlopes suggested that kalfor should be on the list
of awesome vert.x projects.
You can find the project here: https://github.com/derveloper/kalfor

Add kalfor to microservices section

---

README.md

Removing RestVertx

---

README.md

Ceylon impl. is in progress...
The GSOC implementations (Redis, JDBC, Mongo) could/should be added too ! :)

Add (my) Todo-Backend implementations

---

README.md

A fully functional Vert.x client for S3

vertx-s3-client

---

README.md

Added vertx-push-onesignal to Integration

Add vertx-push-onesignal to integration

---

README.md

Added vertxui

---

README.md

Proposal for including example starter application using Gradle

Added example - Vert.x Gradle Starter

---

README.md

Example https://github.com/gentics/mesh-vertx-example for blogpost http://vertx.io/blog/data-driven-apps-made-easy-with-vert-x-3-4-0-and-headless-cms-gentics-mesh/

Add Gentics Mesh example

---

README.md

Modify Zookeeper cluster manger location

Modify Zookeeper cluster manger location

---

README.md

Please consider adding a Smalltalk Event Bus Client link.

Added a Smalltalk Event Bus Client link

---

README.md

https://github.com/katharsis-project/katharsis-framework/issues/320

remove katharsis-vertx, repository has been deleted

---

README.md

I'd like to add my pet project to vertx-awesome. 
Thanks,
Rodolfo

Added crabzilla

---

README.md

See: https://github.com/resilience4j/resilience4j/issues/156

Added Resilience4j to Microservices chapter.

---

README.md

https://github.com/tibor-kocsis/vertx-graphql-utils

Add vertx-graphql-utils

---

README.md

Added a configuration store implementation for the AWS EC2 SSM parameter store. Library is here: https://github.com/Finovertech/vertx-config-aws-ssm

Added com.finovertech:vertx-config-aws-ssm

---

README.md

The main site and documentation is here: https://github.com/GreenfieldTech/irked

Added Irked as a web framework

---

README.md

This is a simple livereload server (http://livereload.com/).
Github projet : https://github.com/ybonnel/vertx-livereload

Add vertx-livereload in development tools.

---

README.md

Nannoq-Tools is a toolkit for constructing robust, scalable and distributed applications leveraging vertx. Currently geared towards AWS, but planned to be expanded to other cloud services and technologies.
Modules:
- Auth
- Cluster
- FCM (Firebase Cloud Messaging)
- Repository
- Web
Check it out at [Nannoq-Tools](https://noriginmedia.github.io/nannoq-tools/)

Added Nannoq-Tools

---

README.md

Hi there,
Would you please consider adding this book to your book section listing.
Thank you in advance

Added Vert.x in Action

---

README.md

Adding Knative sample for vertx-rx

---

README.md

add https://github.com/vert-x3/vertx-cassandra-client

add https://github.com/vert-x3/vertx-cassandra-client

---

README.md

Added entry for [Serverx](https://github.com/lukehutch/serverx) (disclaimer, I am the author).

Add entry for Serverx

---

README.md

closes: https://github.com/vert-x3/vertx-awesome/issues/143

Issue 143: Add The White Rabbit

---

README.md

This is the implementation part of a Master Thesis. It is located [here](https://drive.google.com/file/d/16Nwfh8wMR5eMf7PJ9150F9zSvDUvR4Mz/view?usp=sharing) and this is a brief explanation. A comprehensive description of Autonomous Services is found in the thesis. 
Autonomous Services are Design Principles for Asynchronous and Agnostic Microservice Architectures. It leverages [vert.x](https://github.com/vert-x3) and [nannoq-tools](https://github.com/NoriginMedia/nannoq-tools) to provide an event-based reactive architecure without centralized components, netiher for communication or data, providing a theoretically linear scalability across the architecture.
This repo is a collection of the most current version of all autonomous-services modules.

added autonomous-services

---

README.md

Adds OpenAPI generator

---

README.md

I have added my dependency and api framework. Both are specifically written for Vertx.

Added Glue and API Framework

---

README.md

add new link for section File Serve:
TFTP client for vert.x support upload/download files from TFTP server.
Motivation:
add new library for vert.x that support TFTP Protocol
Conformance:

add new link for TFTP client

---

README.md

add wiremongo

---

README.md

Signed-off-by: jonad <jgarciasm89@gmail.com>
Motivation:
I recently created a template to create APIs with vert.x and I want to share it with the community. This template is intended to help programmers to create an API focusing on the business and also to help them with several examples of how to perform various common tasks.
link: https://github.com/jgarciasm/ssv-api.

add new link for ssv-api

---

README.md

I've been working with Vertx for a long time and it'd be an honor to share all my work with the Vertx community and get some feedback. All the libraries have been uploaded to Maven Central Repos and carefully tested. The readme of each project gives a lot of information about the libraries and how to use them. Thanks.

vertx-effect libraries

---

README.md

Signed-off-by: yaron.elyashiv <yaron.elyashiv@appsflyer.com>
Added [Donkey](https://github.com/AppsFlyer/donkey), Clojure server/client interface over Vert.x to the web frameworks section.

Donkey - https://github.com/AppsFlyer/donkey

---

README.md

Added link to Reactiverse Contextual Logging project

Contextual logging

---

README.md

Motivation:
This PR adds eventbus service to the list. It also introduces a new section for event bus extensions
Link to project: https://github.com/wowselim/eventbus-service
Conformance:

Add eventbus service

---

README.md

Look forward to my elegant little case appearing on your awesome list :)

Add vertx-pmml

---

README.md

vertx-values is a set of codecs to send the JSON from json-values to the EB. It's a persistent JSON, so no need to make defensive copies of the messages.

added new element under section Miscellaneous: vertx-values

---

README.md

Motivation:
I'm the maintainer for Irked, and we have been supporting Vert.x 4 for a while now.

Updated Irked description

---

README.md

Motivation:
Add [vertx-rest](https://github.com/dream11/vertx-rest)
Conformance:

chore: add vertx-rest repository

---

README.md

Motivation:
Adding an InfoQ article https://www.infoq.com/articles/reactive-java-vertx-deep-dive/ 
Conformance:

Add an InfoQ article for Vert.x from Mohit Palriwal
