vert-x3/vertx-awesome

README.md
Example using event bus and service proxies to connect vertx and node - Step by step example with WIKI description showing how to connect Vertx and Node using event bus and service proxies.
=>  Example using event bus and service proxies to connect vertx and node.js

README.md
The Copycat cluster manager is obsolete. This PR replaces it with the Atomix cluster manager, which is based on Copycat.
=> Replaced the Copycat Cluster Manager with Atomix.

README.md
Adds https://github.com/cstamas/vertx-sisu to the list.
Given that project provides:
* SISU/Guice integration
* `vertx-service-factory` alternative
* `verx-maven-service-factory` alternative
I am unsure about proper categorisation, so please suggest.
Project is not yet released (is not in Central), hence am fine waiting with this PR until release happens (expected soon).
Thanks.
=> Add vertx-sisu

README.md
Since vertx-pac4j is now released against vert.x 3, adding information about it to vertx-awesome.
=> Add vertx-pac4j.

README.md
Enlists https://github.com/cstamas/vertx-orientdb to the list.
The project integrates [OrientDB](http://orientdb.com/orientdb/) with Vert.x.
Thanks.
=> vertx-orientdb

README.md
Hello!
I did a implementation,[hystrix-vertx-metrics-steram](https://github.com/kennedyoliveira/hystrix-vertx-metrics-stream), to add the metrics publishing to a vertx application that uses [Netflix Hystrix](https://github.com/Netflix/Hystrix).
=> add hystrix-vertx-metrics-stream

README.md
The latest addition of microservices modules released in 3.3.0 were not there yet....so here they are :)
In the next PR I would like to add this repo to this section: https://github.com/engagingspaces/vertx-graphql-service-discovery
=> Added Microservices section with standard Vert.x modules

README.md
A thin integration layer to use the original Vert.x eventbus.js / sockjs.js 0.3.4 from Dart side. The integration is solved by using the dart:js package.
=> Vert.x-Dart-SockJS integration entry

README.md
A Vert.x client for the NoSQL [Marklogic ](http://www.marklogic.com) database.
=> Vert.x Marklogic entry

README.md
When I submitted vertx-pac4j for inclusion in vertx-awesome I mistakenly marked it as part of the official vert.x stack, as I've just noticed.
This would create an unfair overhead on the vert.x core team, as vertx-pac4j is not part of the offical vert.x stack, so this commit will, if applied, remove the "stack" marker on the library. Sorry for the initial error which has led to the need for this correction
=> Remove erroneous stack marker for vertx-pac4j

README.md
As suggested in the user-group (https://groups.google.com/forum/?fromgroups#!topic/vertx/qlvj-j3UCmI), I've added vertx-jooq. I wasn't sure whether to put it under 'integration' or 'database', but I think it is more likely to be found under the latter.
=> Add vertx-jooq to vertx-awesome

README.md
Added our redesigned version of the https://github.com/englishtown/vertx-elasticsearch-service
=> Redesigned Vert.x Elasticsearch Service

README.md
Proposal to add Knot.x web framework. It depends on Vert.x 3.3.3.
Project repo is [https://github.com/Cognifide/knotx](https://github.com/Cognifide/knotx)
=> Added Knot.x to Web frameworks

README.md
Proposal to add Vert.x Jspare to web framework list. This project is already synchronized with the central maven and I believe it is useful.
=> Added Vert..x Jspare to web frameworks.

README.md
Initial draft done, not yet in Central.
Uses Bitsy 1.5.2 and Vert.x 3.3.3
https://bitbucket.org/lambdazen/bitsy/wiki/Home
=> Bitsy integration

README.md
A Vert.x client for tapping into MySQL replication stream. Based on Vert.x 3.4.1.
It uses [MySQL Binary Log connector](https://github.com/shyiko/mysql-binlog-connector-java) to 
connect to MySQL as a slave and handle the binlog events in a vert.x way.
Initial version is published to Maven Central.
=> Add a MySQL binary log client

README.md
Unfortunately, I don't have the time needed to manage this project and to upgrade to latest versions of Vert.x. It's better it doesn't appear in the list anymore, so that users don't get frustrated discovering the project is using an old Vert.x version.
Maybe I'll add it back when I have time to work on it.
=> Remove Nubes

README.md
This is a starter to build a monolithic CRUD RESTful Web Service with Vert.x stack and postgreSQL. It has been kept up with the newest Vert.x version. Some components introduced in the newest Vert.x 3.5.0 like vertx-web-api-contract and vertx-rx-java2 have been put in use.
=> Add vertx-postgresql-starter to the list

README.md
Just a wrong link in the page.
=> A wrong link

README.md
Utility library for Vert.X that allows using strong-typed interfaces in communication through EventBus.
It's small and easy to use.
=> Adding new reactive library VxRifa

README.md
A simple demonstration of how to deploy Vert.x Java applications on Cloud Foundry using the java-buildpack.
Source code is here: [amdelamar/vertx-cloudfoundry](https://github.com/amdelamar/vertx-cloudfoundry), 
and recently added here: [vert-x3/vertx-examples/cloudfoundry-example](https://github.com/vert-x3/vertx-examples/tree/master/cloudfoundry-example)
=> Add Cloud Foundry demo

README.md
Added https://github.com/zandero/rest.vertx to the list - a Lightweight JAX-RS (RestEasy) like annotation processor for vert.x verticals
=> Added https://github.com/zandero/rest.vertx to the list

README.md
Adding GDH project to miscellaneous. The project is a Java library built on top of Vert.x to allow Generalized Diffie-Hellman key exchange between multiple Vert.x verticles.
=> Adding GDH project

README.md
Vert.x Vaadin lets Vaadin application run on Vert.x instead of servlet environment
Here's a demo running Vaadin 8.3.1 on Vert.x 3.5.1: http://vertx-vaadin-example.herokuapp.com/
Github repository:  https://github.com/mcollovati/vertx-vaadin
=> Add Vert.x Vaadin in Web Frameworks

README.md
Given cluster manager has gotten recently migrated under reactiverse umbrella. Details: https://github.com/reactiverse/reactiverse/issues/3.
=> Updating coordinates of consul cluster manager.

README.md
Add https://github.com/aesteve/vertx-dgraph-client , a very simple example on how to use vertx-grpc-client to access DGraph database.
=> Add Dgraph example

README.md
Add Vert.x [Codegen Gradle Plugin](https://github.com/bulivlad/vertx-codegen-plugin), A Gradle plugin to facilitate the codegen usage for Vert.x Java projects
Disclaimer - I am the author.
=> Add Vert.x Codegen Gradle Plugin

README.md
**RxFirestore Connector Lib URL**: https://github.com/pjgg/rxfirestore
**Short Description**: Non-blocking Gcloud Firestore SDK written in a reactive way.
**Expected section**: NoSQL Databases
=> Add firestore connector lib - Vert.x 3

README.md
https://github.com/korlibs/korte
I have added a new category Template Engines, since I was not able to find a suitable place for it except maybe Miscellaneous.
=> Add KorTE Template Engine for Vert.x 3

README.md
request to remove [vertx-mongo-streams](https://github.com/st-h/vertx-mongo-streams) as I just deprecated it. Mongodb made significant changes to their driver and we do no longer have a need to use the GridFS feature (support of GridFS was vertx-mongo-streams primary feature)
=> remove deprecated vertx-mongo-streams

README.md
Cloudopt Next is a very lightweight and modern, JVM-based, full stack kotlin framework designed for building modular, easily testable JVM applications with support for Java, Kotlin language, crafted from the best of breed Java libraries and standards.
=> add cloudopt-next

README.md
Rust bindings for TCP-Eventbus-bridge
=> Add event-bus-bridge for Rust

README.md
I just released our Vert.x-based WAMP broker as Open Source. It's quite basic - i.e. no RPC Dealer or Advanced Profile at the moment -, so not sure how awesome it is in the grand scheme of things but maybe someone else will find it useful, too.
=> Add vertx-wamp reference

README.md
Motivation:
Add Vertx scheduler
Conformance:
=> Add Vertx scheduler

README.md
Signed-off-by: Srijan Gupta <srijan02420@gmail.com>
Motivation:
Adding link to [vertx-aerospike-client](https://github.com/dream11/vertx-aerospike-client).
The Vert.x Aerospike client provides an asynchronous API to interact with aerospike server. (Internally uses AerospikeClient's async commands and handles the result on vertx-context).
=> add async aerospike client

README.md
Motivation:
The [MongoDB repo](https://github.com/imrafaelmerino/vertx-mongo-effect) updated.
Conformance:
=> MongoDB client repo updated

README.md
Motivation:
[Exposed](https://github.com/JetBrains/Exposed) is a popular ORM framework for Kotiln but runs in the blocking way. [This Exposed Vert.x SQL Client library](https://github.com/huanshankeji/exposed-vertx-sql-client) provides code to integrate Exposed on top of Vert.x Reactive SQL Client, combining ease of use from an ORM and efficiency from Vert.x's reactive/non-blocking approach.
Conformance:
=> Add the Exposed Vert.x SQL Client library
